# docker compose ve por defecto el archivo .env
version: '3'
services:
  db:
    image: postgres:16
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    container_name: ${DB_CONTAINER_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data